config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: %i[index show new create edit update destroy] do
    resources :stock_product_destinations, only: [:create]
  end

  resources :suppliers, only: %i[index show new create edit update]
  resources :product_models, only: %i[index show new create]

  resources :orders, only: %i[index new create show edit update] do
    resources :order_items, only: %i[new create]
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models

  validates :corporate_name, :brand_name, :registration_number, :full_address, :city, :state, :email, :phone_number,
            presence: true
  validates :registration_number, uniqueness: true
  validates :registration_number, cnpj: true

  def sup_description
    "#{brand_name} - #{corporate_name} - #{registration_number}"
  end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[show edit update]

  def index
    @suppliers = Supplier.all
  end

  def show; end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to @supplier, notice: 'Fornecedor cadastrado com sucesso'
    else
      flash.now[:alert] = 'Fornecedor não cadastrado'
      render 'new'
    end
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_path(@supplier.id), notice: 'Fornecedor atualizado com sucesso'
    else
      flash.now[:alert] = 'Não foi possível atualizar o fornecedor'
      render 'edit'
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, :city, :state,
                                     :email, :phone_number)
  end
end

app/views/suppliers/_sup_form.html.erb
<%= form_with(model: @supplier) do |f| %>
  <div>
    <%= f.label :corporate_name %>
    <%= f.text_field :corporate_name %>
  </div>
  <div>
    <%= f.label :brand_name %>
    <%= f.text_area :brand_name %>
  </div>
  <div>
    <%= f.label :full_address %>
    <%= f.text_field :full_address %>
  </div>
  <div>
    <%= f.label :registration_number %>
    <%= f.number_field :registration_number %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :phone_number %>
    <%= f.telephone_field :phone_number %>
  </div>
  <div>
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1><%= Supplier.human_attribute_name(:edit_supplier)%></h1>
<% if(@supplier.errors.any?) %>
  <p><%= Supplier.human_attribute_name(:check_the_errors)%>:</p>
  <ul>
    <% @supplier.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'sup_form' %>

app/views/suppliers/index.html.erb
<h1><%= Supplier.human_attribute_name(:suppliers)%></h1>

<%= link_to 'Cadastrar novo fornecedor', new_supplier_path %>

<% if @suppliers.any? %>
  <table>
    <thead>
      <tr>
        <th><%= Supplier.human_attribute_name(:name)%></th>
        <th><%= Supplier.human_attribute_name(:location)%></th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= link_to supplier.brand_name, supplier %></td>
          <td><%= supplier.city %> - <%= supplier.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><%= Supplier.human_attribute_name(:no_registered_suppliers)%></p>
<% end %>

app/views/suppliers/new.html.erb
<h1><%= Supplier.human_attribute_name(:new_supplier)%></h1>
<% if(@supplier.errors.any?) %>
  <p><%= Supplier.human_attribute_name(:check_the_errors)%>:</p>
  <ul>
    <% @supplier.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'sup_form' %>

app/views/suppliers/show.html.erb
<h1> <%= Supplier.model_name.human %> <%= @supplier.brand_name %></h1>
<h2><%= @supplier.corporate_name %></h2>
<dl>
  <dt><%= Supplier.human_attribute_name(:document)%>:</dt>
  <dd><%= @supplier.registration_number %></dd>
  <dt><%= Supplier.human_attribute_name(:full_address)%>:</dt>
  <dd><%= @supplier.full_address %> - <%= @supplier.city %> - <%= @supplier.state %></dd>
  <dt><%= Supplier.human_attribute_name(:email)%>:</dt>
  <dd><%= @supplier.email %></dd>
  <dt><%= Supplier.human_attribute_name(:phone_number)%>:</dt>
  <dd><%= @supplier.phone_number %></dd>
</dl>


<% @products = @supplier.product_models.all%>
<div>
  <% @products.each do |prod| %>
    <h2><%= link_to prod.name, prod %></h2>
  </div>
<% end %>


<div>
  <%= link_to 'Editar', edit_supplier_path(@supplier)%>
</div>
<div>
  <%= link_to 'Voltar', root_path %>
</div>